const emailTemplates = {
  en: {
    otp_subject: "Verification Code - Internshala",
    password_reset_title: "Password Reset Request",
    password_reset_body: "You requested a password reset. Use the OTP below to reset your password:",
    chrome_login_title: "Chrome Login Verification",
    chrome_login_body: "A new login was detected on Chrome. Use the OTP below to verify your identity:",
    resume_otp_title: "Resume Creation Verification",
    resume_otp_body: "To proceed with resume creation, please verify your email with the OTP below:",
    resume_receipt_subject: "Resume Creation Payment Receipt - Internshala",
    resume_receipt_title: "Payment Successful!",
    resume_receipt_body: "Your payment for resume creation has been successfully processed.",
    subscription_invoice_subject: "Payment Invoice - {planName}",
    subscription_invoice_title: "Payment Successful!",
    subscription_invoice_subtitle: "Invoice Details",
    otp_expiry_msg: "This OTP will expire in 10 minutes. If you didn't request this, please ignore this email.",
    amount_paid: "Amount Paid",
    payment_id: "Payment ID",
    order_id: "Order ID",
    date_label: "Date",
    view_subscription: "View Subscription"
  },
  es: {
    otp_subject: "Código de Verificación - Internshala",
    password_reset_title: "Solicitud de Restablecimiento de Contraseña",
    password_reset_body: "Solicitaste restablecer tu contraseña. Usa el OTP a continuación para restablecerla:",
    chrome_login_title: "Verificación de Inicio de Sesión en Chrome",
    chrome_login_body: "Se detectó un nuevo inicio de sesión en Chrome. Usa el OTP a continuación para verificar tu identidad:",
    resume_otp_title: "Verificación de Creación de Currículum",
    resume_otp_body: "Para proceder con la creación del currículum, verifica tu correo con el OTP a continuación:",
    resume_receipt_subject: "Recibo de Pago de Creación de Currículum - Internshala",
    resume_receipt_title: "¡Pago Exitoso!",
    resume_receipt_body: "Tu pago para la creación del currículum ha sido procesado con éxito.",
    subscription_invoice_subject: "Factura de Pago - {planName}",
    subscription_invoice_title: "¡Pago Exitoso!",
    subscription_invoice_subtitle: "Detalles de la Factura",
    otp_expiry_msg: "Este OTP expirará en 10 minutos. Si no solicitaste esto, ignora este correo.",
    amount_paid: "Monto Pagado",
    payment_id: "ID de Pago",
    order_id: "ID de Pedido",
    date_label: "Fecha",
    view_subscription: "Ver Suscripción"
  },
  hi: {
    otp_subject: "सत्यापन कोड - Internshala",
    password_reset_title: "पासवर्ड रीसेट अनुरोध",
    password_reset_body: "आपने पासवर्ड रीसेट करने का अनुरोध किया है। अपना पासवर्ड रीसेट करने के लिए नीचे दिए गए OTP का उपयोग करें:",
    chrome_login_title: "Chrome लॉगिन सत्यापन",
    chrome_login_body: "Chrome पर एक नया लॉगिन पाया गया। अपनी पहचान सत्यापित करने के लिए नीचे दिए गए OTP का उपयोग करें:",
    resume_otp_title: "रेज़्यूमे निर्माण सत्यापन",
    resume_otp_body: "रेज़्यूमे निर्माण के साथ आगे बढ़ने के लिए, कृपया नीचे दिए गए OTP के साथ अपना ईमेल सत्यापित करें:",
    resume_receipt_subject: "रेज़्यूमे निर्माण भुगतान रसीद - Internshala",
    resume_receipt_title: "भुगतान सफल!",
    resume_receipt_body: "रेज़्यूमे निर्माण के लिए आपका भुगतान सफलतापूर्वक संसाधित किया गया है।",
    subscription_invoice_subject: "भुगतान चालान - {planName}",
    subscription_invoice_title: "भुगतान सफल!",
    subscription_invoice_subtitle: "चालान विवरण",
    otp_expiry_msg: "यह OTP 10 मिनट में समाप्त हो जाएगा। यदि आपने इसका अनुरोध नहीं किया है, तो कृपया इस ईमेल को अनदेखा करें।",
    amount_paid: "भुगतान की गई राशि",
    payment_id: "भुगतान आईडी",
    order_id: "ऑर्डर आईडी",
    date_label: "तारीख",
    view_subscription: "सदस्यता देखें"
  },
  pt: {
    otp_subject: "Código de Verificação - Internshala",
    password_reset_title: "Solicitação de Redefinição de Senha",
    password_reset_body: "Você solicitou uma redefinição de senha. Use o OTP abaixo para redefinir sua senha:",
    chrome_login_title: "Verificação de Login no Chrome",
    chrome_login_body: "Um novo login foi detectado no Chrome. Use o OTP abaixo para verificar sua identidade:",
    resume_otp_title: "Verificação de Criação de Currículo",
    resume_otp_body: "Para prosseguir com a criação do currículo, verifique seu e-mail com o OTP abaixo:",
    resume_receipt_subject: "Recibo de Pagamento de Criação de Currículo - Internshala",
    resume_receipt_title: "Pagamento Bem-sucedido!",
    resume_receipt_body: "Seu pagamento para criação de currículo foi processado com sucesso.",
    subscription_invoice_subject: "Fatura de Pagamento - {planName}",
    subscription_invoice_title: "Pagamento Bem-sucedido!",
    subscription_invoice_subtitle: "Detalhes da Fatura",
    otp_expiry_msg: "Este OTP expirará em 10 minutos. Se você não solicitou isso, desconsidere este e-mail.",
    amount_paid: "Valor Pago",
    payment_id: "ID do Pagamento",
    order_id: "ID do Pedido",
    date_label: "Data",
    view_subscription: "Ver Assinatura"
  },
  zh: {
    otp_subject: "验证码 - Internshala",
    password_reset_title: "密码重置请求",
    password_reset_body: "您请求重置密码。请使用下面的验证码重置您的密码：",
    chrome_login_title: "Chrome 登录验证",
    chrome_login_body: "在 Chrome 上检测到新登录。请使用下面的验证码验证您的身份：",
    resume_otp_title: "简历创建验证",
    resume_otp_body: "要继续创建简历，请使用下面的验证码验证您的电子邮件：",
    resume_receipt_subject: "简历创建付款收据 - Internshala",
    resume_receipt_title: "付款成功！",
    resume_receipt_body: "您的简历创建付款已成功处理。",
    subscription_invoice_subject: "付款发票 - {planName}",
    subscription_invoice_title: "付款成功！",
    subscription_invoice_subtitle: "发票详情",
    otp_expiry_msg: "此验证码将在 10 分钟后过期。如果您没有请求此操作，请忽略此电子邮件。",
    amount_paid: "已付金额",
    payment_id: "付款 ID",
    order_id: "订单 ID",
    date_label: "日期",
    view_subscription: "查看订阅"
  },
  fr: {
    otp_subject: "Code de vérification - Internshala",
    password_reset_title: "Demande de réinitialisation de mot de passe",
    password_reset_body: "Vous avez demandé une réinitialisation de mot de passe. Utilisez l'OTP ci-dessous pour réinitialiser votre mot de passe:",
    chrome_login_title: "Vérification de connexion Chrome",
    chrome_login_body: "Une nouvelle connexion a été détectée sur Chrome. Utilisez l'OTP ci-dessous pour vérifier votre identité:",
    resume_otp_title: "Vérification de la création de CV",
    resume_otp_body: "Pour procéder à la création de votre CV, veuillez vérifier votre e-mail avec l'OTP ci-dessous:",
    resume_receipt_subject: "Reçu de paiement pour la création de CV - Internshala",
    resume_receipt_title: "Paiement réussi !",
    resume_receipt_body: "Votre paiement pour la création de CV a été traité avec succès.",
    subscription_invoice_subject: "Facture de paiement - {planName}",
    subscription_invoice_title: "Paiement réussi !",
    subscription_invoice_subtitle: "Détails de la facture",
    otp_expiry_msg: "Cet OTP expirera dans 10 minutes. Si vous n'avez pas demandé cela, veuillez ignorer cet e-mail.",
    amount_paid: "Montant payé",
    payment_id: "ID de paiement",
    order_id: "ID de commande",
    date_label: "Date",
    view_subscription: "Voir l'abonnement"
  }
};

module.exports = emailTemplates;
